# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
      colorArg: always
gui:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers
  border: single
  theme:
      activeBorderColor:
          - "#7dcfff"
      inactiveBorderColor:
          - "#565f89"
      searchingActiveBorderColor:
          - "#ff5ef1"
      optionsTextColor:
          - "#292e42"
      selectedLineBgColor:
          - "#292e42"
      cherryPickedCommitBgColor:
          - "#292e42"
      cherryPickedCommitFgColor:
          - "#ff5ea0"
      unstagedChangesColor:
          - "#ffbd5e"
      defaultFgColor:
          - "#c0caf5"
