bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi r send -X rectangle-toggle

bind r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind c new-window -c "#{pane_current_path}"
bind '-' split-window -h -c "#{pane_current_path}"
bind 'v' split-window -v -c "#{pane_current_path}"

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

set -g @tl "$HOME/.config/tmux/scripts"
bind f display-menu -T "#[align=centre] Launcher" -x R -y P \
  "Windows"   i "run-shell '#{@tl}/windows.sh'" \
  "Sessions"  w "run-shell '#{@tl}/sessions.sh'" \
  "Dotfiles"  c "run-shell '#{@tl}/dotfiles.sh'" \
  "Layouts"   l "run-shell '#{@tl}/layouts.sh'" \
  "" \
  "Zoxide"    o "run-shell '#{@tl}/zoxide.sh'" \
  "yazi"      f "run-shell -b '#{@tl}/yazi.sh'" \
  "yazi ~"    F "run-shell -b '#{@tl}/yazi.sh ~'" \
  "lazygit"   g "run-shell -b '#{@tl}/lazygit.sh'"
