bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi r send -X rectangle-toggle

bind r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded"

# # Smart pane switching with awareness of Vim splits.
# # See: https://github.com/christoomey/vim-tmux-navigator
# vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
# is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
#     | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
# bind-key -n 'M-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
# bind-key -n 'M-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
# bind-key -n 'M-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
# bind-key -n 'M-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
# tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
# if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
#     "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
# if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
#     "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"
#
# bind-key -T copy-mode-vi 'M-h' select-pane -L
# bind-key -T copy-mode-vi 'M-j' select-pane -D
# bind-key -T copy-mode-vi 'M-k' select-pane -U
# bind-key -T copy-mode-vi 'M-l' select-pane -R
# bind-key -T copy-mode-vi 'C-\' select-pane -l

bind c new-window -c "#{pane_current_path}"
bind '-' split-window -h -c "#{pane_current_path}"
bind 'v' split-window -v -c "#{pane_current_path}"

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

set -g @tl "$HOME/.config/tmux/scripts"
bind f display-menu -T "#[align=centre] Launcher" -x R -y P \
  "Windows"   i "run-shell '#{@tl}/windows.sh'" \
  "Sessions"  w "run-shell '#{@tl}/sessions.sh'" \
  "Dotfiles"  c "run-shell '#{@tl}/dotfiles.sh'" \
  "Layouts"   l "run-shell '#{@tl}/layouts.sh'" \
  "" \
  "yazi"      f "run-shell -b '#{@tl}/yazi.sh'" \
  "yazi ~"    F "run-shell -b '#{@tl}/yazi.sh ~'" \
  "lazygit"   g "run-shell -b '#{@tl}/lazygit.sh'"

bind-key o run-shell "#{@tl}/zoxide.sh"
