set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_toggle 'p'
set -g @pomodoro_on ' 󰥔 '
set -g @pomodoro_complete ' 󰄬 '
set -g @pomodoro_pause ' 󰏤 '
set -g @pomodoro_break ' 󰔟 '
set -g @pomodoro_notifications 'on'

set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @smart-splits_no_wrap '' 

set -g @smart-splits_move_left_key  'M-h' 
set -g @smart-splits_move_down_key  'M-j'
set -g @smart-splits_move_up_key    'M-k'
set -g @smart-splits_move_right_key 'M-l'

set -g @smart-splits_resize_left_key  'M-H'
set -g @smart-splits_resize_down_key  'M-J'
set -g @smart-splits_resize_up_key    'M-K'
set -g @smart-splits_resize_right_key 'M-L'

set -g @smart-splits_resize_step_size '10'

if-shell "test ! -d ~/.tmux/plugins/tpm" \
  "run-shell 'git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm >/dev/null 2>&1'"
run '~/.tmux/plugins/tpm/tpm'
