set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'jimeh/tmuxifier'

set -g @plugin 'olimorris/tmux-pomodoro-plus'
set -g @pomodoro_toggle 'p'
set -g @pomodoro_on ' 󰄉 '
set -g @pomodoro_complete ' 󰄬 '
set -g @pomodoro_pause ' 󰏤 '
set -g @pomodoro_break ' 󰔡 '
set -g @pomodoro_notifications 'on'

if-shell "test ! -d ~/.tmux/plugins/tpm" \
  "run-shell 'git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm >/dev/null 2>&1'"
run '~/.tmux/plugins/tpm/tpm'
