set -g @c_fg "#c0caf5"
set -g @c_muted "#565f89"
set -g @c_accent "#89b4fa"
set -g @c_green "#5eff6c"
set -g @c_bg "default"
set -g @c_border "#292e42"

set -g status-style "bg=#{@c_bg},fg=#{@c_fg}"
set -g status-left "#[fg=#5eff6c,bold]+ #[default]"
set -g status-right "\
#{pomodoro_status} \
#[fg=#{@c_fg}]#S \
#[fg=#{@c_muted}]@ \
#[fg=#{@c_green},bold]#(whoami) \
#[fg=#{@c_muted}]· on · \
#[fg=#{@c_accent},bold]#H"

set -g window-status-format "#[fg=#{@c_muted}]#I #W"
set -g window-status-current-format "#[fg=white,bold]#I #W"
set -g window-status-separator " "

set -g pane-border-style "fg=#{@c_border}"
set -g pane-active-border-style "fg=#{@c_accent}"

set -g mode-style "bg=#292e42,fg=#c0caf5"
set -g message-style "bg=#292e42,fg=#c0caf5"

set -g menu-style "bg=#16161e,fg=#c0caf5"
set -g menu-border-style "fg=#89b4fa"
set -g menu-selected-style "bg=#292e42,fg=#7dcfff"

set -g popup-border-style "fg=#89b4fa"
