set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g allow-passthrough on
set -g set-clipboard on
set -s extended-keys off
set -s escape-time 10
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

setw -g mode-keys vi

set -g automatic-rename off
set -g status-position top

set -g @launcher-picker-width "50%"
set -g @launcher-picker-height "40%"
set -g @launcher-app-width "90%"
set -g @launcher-app-height "90%"
set -g @launcher-editor "nvim"

unbind C-b
set -g prefix C-a
bind C-a send-prefix
