set -g @c_fg "#8b95a5"
set -g @c_muted "#4f5866"
set -g @c_accent "#3b82f6"
set -g @c_green "#5effc3"
set -g @c_bg "default"
set -g @c_border "#1e293b"

set -g status-style "bg=#{@c_bg},fg=#{@c_fg}"
set -g status-left "#[fg=#5effc3,bold]+ #[default]"
set -g status-right "\
#[fg=#{@c_fg}]#S \
#[fg=#{@c_muted}]@ \
#[fg=#{@c_green},bold]#(whoami) \
#[fg=#{@c_muted}]· on · \
#[fg=#{@c_accent},bold]#H"

set -g window-status-format "#[fg=#{@c_muted}]#I #W"
set -g window-status-current-format "#[fg=white,bold]#I #W"
set -g window-status-separator " "

set -g pane-border-style "fg=#{@c_border}"
set -g pane-active-border-style "fg=#{@c_accent}"

set -g mode-style "bg=#253547,fg=white"
set -g message-style "bg=#253547,fg=white"
