require("tree-sitter-manager").setup({
  ensure_installed = {
    "bash",
    "css",
    "go",
    "gomod",
    "gosum",
    "html",
    "http",
    "javascript",
    "json",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "rust",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
  },
  highlight = true,
  auto_install = true,
})
